services:
  # Application
  backend:
    image: backend-app:latest
    build:
      context: ../source/App.Backend
    ports:
    - "5000:5000"
    environment:
    - dbconnection=mongodb://mongodb:27017
    depends_on:
    - mongodb

  frontend:
    image: frontend-app:latest
    build:
      context: ../source/App.Frontend
    ports:
      - "3000:80"
    depends_on:
    - backend

  # Sample database service
  mongodb:
    build:
      context: ../source/MongoDB
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: RageCraft
      MONGO_INITDB_ROOT_PASSWORD: minenostalgia7!
    ports:
    - "27017:27017"
    volumes:
    - ../source/MongoDB/mongo-data:/data/db

volumes:
  mongo-data:
